---
name: Push README

on:
  push:
    branches:
      - main
      - master
    paths:
      - "README.md"
      - "README-containers.md"
      - ".github/workflows/container_description.yml"

permissions: {}

jobs:

  PushDockerHubReadme:
    name: Push README to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set docker hub repo name
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_HUB_ORG }}
        run: echo "DOCKER_REPO_NAME=$(DOCKER_REPO="$DOCKER_REPO" make docker-repo-name)" >> "$GITHUB_ENV"

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_LOGIN }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
        with:
          destination_container_repo: ${{ env.DOCKER_REPO_NAME }}
          provider: dockerhub
          short_description: ${{ env.DOCKER_REPO_NAME }}
          readme_file: 'README.md'
